FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt
RUN rm /app/requirements.txt

COPY src/ /app/src
COPY protos /app/protos
COPY scripts /app/scripts

RUN chmod +x /app/scripts/run.sh

RUN python -m grpc_tools.protoc \
    -I /app/protos \
    --python_out=/app/src/protos \
    $(find /app/protos -name "*.proto")

